## Упражнения по библиотеке Numpy

In [2]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [3]:
np.random.seed(17)

random_numbers = np.random.randint(low= 1, high= 20, size = 7, dtype = "l")
resulting_numbers = np.where(((random_numbers > 3) & (random_numbers < 8)), random_numbers *-1, random_numbers)
print(f'Initial array: {random_numbers}, Resulting array : {resulting_numbers}')

Initial array: [16 18 16  7 17 14  5], Resulting array : [16 18 16 -7 17 14 -5]


**2.** Заменить максимальный элемент случайного массива на 0

In [4]:
replaced_numbers = np.where(random_numbers == np.max(random_numbers), 0, random_numbers)
print(f'Resulting array : {replaced_numbers}')

Resulting array : [16  0 16  7 17 14  5]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [8]:
random_matrix = np.random.randint(1, 20, size=(2, 2))
flat = random_matrix.flatten()

a, b = np.meshgrid(flat, flat)

res = np.stack([a, b], axis=-1)

print("Initial matrix:\n", random_matrix)
print("Result:\n", res)
# your code

Initial matrix:
 [[10 18]
 [15 14]]
Result:
 [[[10 10]
  [18 10]
  [15 10]
  [14 10]]

 [[10 18]
  [18 18]
  [15 18]
  [14 18]]

 [[10 15]
  [18 15]
  [15 15]
  [14 15]]

 [[10 14]
  [18 14]
  [15 14]
  [14 14]]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [6]:
B = np.array([
    [1, 2],
    [3, 4]
])
A = np.array([
    [1, 2, 5],
    [3, 4, 6],
    [7, 8, 9],
    [2, 3, 4], #here
    [4, 5, 6],
    [1, 3, 5], # here
    [2, 4, 6], # here
    [0, 1, 4]  # here
])
mask = (np.any(np.isin(A, B[0]), axis=1) & np.any(np.isin(A, B[1]), axis=1))
result = A[mask]
print(f'Filtered array A: {result}')
# your code

Filtered array A: [[2 3 4]
 [1 3 5]
 [2 4 6]
 [0 1 4]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [7]:
A = np.array([
    [1, 1, 1],  # here
    [2, 2, 3],
    [4, 5, 4],
    [7, 7, 7],  # here
    [0, 1, 2],
    [3, 3, 2],
    [5, 6, 7],
    [9, 9, 9],  # here
    [4, 4, 5],
    [8, 7, 8]
])

mask = ~ ((A[:,0] == A[:,1]) & (A[:,1] == A[:,2]))

print(f'Filtered array A: {A[mask]}')
# your code

Filtered array A: [[2 2 3]
 [4 5 4]
 [0 1 2]
 [3 3 2]
 [5 6 7]
 [4 4 5]
 [8 7 8]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [8]:
A = np.array([
    [1, 1, 1],  # here
    [2, 2, 3],
    [4, 5, 4],
    [1, 1, 1],  # here
    [0, 1, 2],
    [3, 3, 2],
    [5, 6, 7],
    [1, 1, 1],  # here
    [4, 4, 5],
    [8, 7, 8]
])

filtered = np.unique(A, axis=0)
print(f'Filtered array A: {filtered}')
# your code

Filtered array A: [[0 1 2]
 [1 1 1]
 [2 2 3]
 [3 3 2]
 [4 4 5]
 [4 5 4]
 [5 6 7]
 [8 7 8]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [9]:
X = np.array([[1, 0, 1],
              [2, 0, 2],
              [3, 0, 3],
              [4, 4, 4]])

arr = X[((np.eye(*X.shape)).astype(bool)) & (X > 0)]
mult = np.cumprod(arr)
print(f'The result of multiplication is {mult[-1]}')# your code

The result of multiplication is 3


In [10]:
lst = [[1, 0, 1],
      [2, 0, 2],
      [3, 0, 3],
      [4, 4, 4]]
mult = 1
for i, elem in enumerate(lst):
    for j, el in enumerate(elem):
        if i == j and el != 0:
           mult *= el
print(f'The result of multiplication is {mult}')

The result of multiplication is 3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [11]:
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

print(f'Are the multisets identical: {np.all(np.bincount(x) == np.bincount(y))}')
# your code

Are the multisets identical: True


In [12]:
x = [1, 2, 2, 4]
y = [4, 2, 1, 2]

x.sort()
y.sort()

print(f'Are the multisets identical: {x == y}')

Are the multisets identical: True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [50]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
mask = (x == 0)
filtered = x[np.insert(mask[:-1], 0, False)]
print(f'Max value after 0: {np.max(filtered)}')
# your code

Max value after 0: 5


In [14]:
lst = [6, 2, 0, 3, 0, 0, 5, 7, 0]
max_l = min(lst)
for i, l in enumerate(lst):
    if l > max_l and lst[i-1] == 0 and i != 0:
        max_l = l
print(f'Max value after 0: {max_l}')

Max value after 0: 5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [23]:
x = np.array([2, 2, 2, 3, 3, 3, 5])

diff = np.diff(x)
idx = np.where(diff != 0)[0] + 1

values = np.split(x, idx)
values = np.array([v[0] for v in values])

counts = np.array([len(v) for v in np.split(x, idx)])

print(f'Values are: {values}, Repeat them {counts} times')
# your code

Values are: [2 3 5], Repeat them [3 3 1] times


In [22]:
x = [2, 2, 2, 3, 3, 3, 5]

values = []
counts = []

current_value = x[0]
current_count = 1

for elem in x[1:]:
    if elem == current_value:
        current_count += 1
    else:
        values.append(current_value)
        counts.append(current_count)
        current_value = elem
        current_count = 1


values.append(current_value)
counts.append(current_count)

print(f'Values are: {values}, Repeat them {counts} times')

Values are: [2, 3, 5], Repeat them [3, 3, 1] times


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [104]:
# your code

np.random.seed(17)

X = np.random.randint(low=1, high=50, size=(1000,2), dtype="l")
Y = np.random.randint(low=1, high=50, size=(500,2), dtype="l")

X_expanded = X[:, None, :]
Y_expanded = Y[None, :, :]

np.sqrt(np.sum(np.pow(X_expanded - Y_expanded, 2), axis=2))


array([[22.36067977, 22.36067977, 24.69817807, ..., 28.0713377 ,
        15.        , 32.75667871],
       [21.21320344, 27.01851217, 31.30495168, ..., 15.8113883 ,
        33.12099032,  9.        ],
       [29.        , 45.17742799, 16.64331698, ..., 43.18564576,
        41.10960958, 40.22437072],
       ...,
       [29.69848481, 21.02379604, 34.92849839, ..., 30.3644529 ,
        13.15294644, 37.58989226],
       [27.85677655, 39.69886648, 33.01514804, ..., 28.42534081,
        44.68780594, 19.10497317],
       [24.18677324, 42.72001873, 21.47091055, ..., 33.24154028,
        44.72135955, 24.        ]], shape=(1000, 500))

In [12]:
import scipy
np.random.seed(17)

X = np.random.randint(low=1, high=50, size=(1000,2), dtype="l")
Y = np.random.randint(low=1, high=50, size=(500,2), dtype="l")

scipy.spatial.distance.cdist(X, Y)

array([[22.36067977, 22.36067977, 24.69817807, ..., 28.0713377 ,
        15.        , 32.75667871],
       [21.21320344, 27.01851217, 31.30495168, ..., 15.8113883 ,
        33.12099032,  9.        ],
       [29.        , 45.17742799, 16.64331698, ..., 43.18564576,
        41.10960958, 40.22437072],
       ...,
       [29.69848481, 21.02379604, 34.92849839, ..., 30.3644529 ,
        13.15294644, 37.58989226],
       [27.85677655, 39.69886648, 33.01514804, ..., 28.42534081,
        44.68780594, 19.10497317],
       [24.18677324, 42.72001873, 21.47091055, ..., 33.24154028,
        44.72135955, 24.        ]], shape=(1000, 500))

scipy.spatial.distance.cdist на больших выборках работает быстрее

In [25]:
import math

np.random.seed(17)
X = np.random.randint(1, 50, size=(1000, 2))
Y = np.random.randint(1, 50, size=(500, 2))

dist = []
for x1, x2 in X:
    row = []
    for y1, y2 in Y:
        dx = x1 - y1
        dy = x2 - y2
        row.append(math.sqrt(dx*dx + dy*dy))
    dist.append(row)

print(dist[0][:10])

[22.360679774997898, 22.360679774997898, 24.698178070456937, 10.295630140987, 26.076809620810597, 41.86884283091664, 37.33630940518894, 21.470910553583888, 27.51363298439521, 23.323807579381203]


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [18]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [123]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [28]:
mean_calories = np.round(np.mean(calorie_stats), 2)
print(f'Mean calories amount = {mean_calories}')

# your code

Mean calories amount = 106.88


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [29]:
calorie_stats_sorted = np.sort(calorie_stats, axis=-1, kind=None, order=None)
calorie_stats_sorted
# your code

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [32]:
median_calories = np.median(calorie_stats)
print(f'Median calories amount = {median_calories}')# your code

Median calories amount = 110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [113]:
perc = np.percentile(calorie_stats, 3.29)
print(f'3.29th percentile = {perc}')
# your code

3.29th percentile = 60.007999999999996


In [112]:
print(round(perc, 2))
for i in range(25):
    perc = np.percentile(calorie_stats, i)
    if 50 < perc < 70:
        nth_percentile = i
print(nth_percentile)

60.01
3


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [114]:
more_calories = 100 - nth_percentile

more_calories
# your code

97

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [115]:
calorie_std = np.std(calorie_stats, axis=None, dtype=None, ddof=0)
print(round(calorie_std, 2))
# your code

19.36


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [127]:
# your code
print(f"На рынке представлено более {len(calorie_stats)} марок сухих завтраков. Анализ показал существенную вариативность калорийности: диапазон составляет от {np.min(calorie_stats) } до {np.max(calorie_stats) } ккал на 100 г, стандартное отклонение — {round(calorie_std)}.")

print(f"Средняя калорийность продуктов — {mean_calories} ккал, при этом более половины ассортимента приходится на позиции с калорийностью {median_calories} ккал и выше.")

print(f"Исследуемый продукт входит в нижние {round(nth_percentile)}% рынка по калорийности ({nth_percentile}-й перцентиль) — его показатель составляет 60 ккал на 100 г. Примерно {more_calories}% продуктов имеют более высокую калорийность.")
print(f"С учётом того, что основным источником энергии в большинстве сухих завтраков являются быстрые углеводы, высокая калорийность означает короткое насыщение при большем суммарном потреблении энергии. На этом фоне продукт с низкой энергетической плотностью представляет собой более лёгкую альтернативу большинству предложений рынка.")



На рынке представлено более 77 марок сухих завтраков. Анализ показал существенную вариативность калорийности: диапазон составляет от 50.0 до 160.0 ккал на 100 г, стандартное отклонение — 19.
Средняя калорийность продуктов — 110.0 ккал, при этом более половины ассортимента приходится на позиции с калорийностью 110.0 ккал и выше.
Исследуемый продукт входит в нижние 3% рынка по калорийности (3-й перцентиль) — его показатель составляет 60 ккал на 100 г. Примерно 97% продуктов имеют более высокую калорийность.
С учётом того, что основным источником энергии в большинстве сухих завтраков являются быстрые углеводы, высокая калорийность означает короткое насыщение при большем суммарном потреблении энергии. На этом фоне продукт с низкой энергетической плотностью представляет собой более лёгкую альтернативу большинству предложений рынка.
